language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9

otp_release:
  - 20.0
  - 21.0
  - 22.0

sudo: required

services:
  - docker

before_script:
  - make code-analysis
  # - make dialyzer

script:
  - make test_ci

after_script:
  - make doc

cache:
  directories:
    - priv/plts
